### ISSUE TITLE
Practica 2

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-buscadores-de-datos#1]
[REPORTE PRACTICA2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-buscadores-de-datos/files/14306062/REPORTE.PRACTICA2.pdf)

* Ariadna Monserrat López Aparicio
• Roldan Uriel Arcadio Ávila
• Pedro García García

**Comment by Anakimberly** [comment]
95/100 tiene faltas de ortografía

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
